version: '3.3'
services:
  mongodb:
    # container name
    container_name: mongodb
    # container image:version/-tag
    image: mongo
    # host:container ports binded
    ports:
      - 6003:27017
    # environment variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongoexpress:
    container_name: mongoexpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass